#! /bin/bash
set -e

pip install -r requirements.txt
pip install -i https://testpypi.python.org/pypi tfinterface
echo
echo "Testing Library:"
echo
python -c "import tfinterface; print('Hello from python. Phi version:', tfinterface.__version__)"